package org.roboquant.common;

import java.time.Instant;
import java.time.Duration;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;

/**
 * TimeSpan is an immutable class that unifies the JVM classes Duration and Period and allows to use them
 * more easily in your code. It can store time-spans as small as nanoseconds.
 * It is modeled after the time duration, as described in ISO 8601.
 */
public class TimeSpan {

    private final Period period;
    private final Duration duration;

    /**
     * TimeSpan of 0
     */
    public static final TimeSpan ZERO = new TimeSpan();

    /**
     * Create a new instance of TimeSpan.
     */
    public TimeSpan() {
        this(0, 0, 0, 0, 0, 0, 0L);
    }

    /**
     * Create a new instance of TimeSpan.
     */
    public TimeSpan(int years, int months, int days, int hours, int minutes, int seconds, long nanos) {
        this.period = Period.of(years, months, days).normalized();
        this.duration = createDuration(hours, minutes, seconds, nanos);
    }

    /**
     * Internal constructor.
     */
    private TimeSpan(Period period, Duration duration) {
        this.period = period;
        this.duration = duration;
    }

    /**
     * Create a Duration instance based on hours, seconds and nanos.
     */
    private static Duration createDuration(int hours, int minutes, int seconds, long nanos) {
        Duration result = Duration.ZERO;
        if (hours != 0) result = result.plusHours(hours);
        if (minutes != 0) result = result.plusMinutes(minutes);
        if (seconds != 0) result = result.plusSeconds(seconds);
        if (nanos != 0L) result = result.plusNanos(nanos);
        return result;
    }

    /**
     * Checks if this is a zero TimeSpan.
     */
    public boolean isZero() {
        return period.isZero() && duration.isZero();
    }

    /**
     * Get the period component.
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Get the duration component.
     */
    public Duration getDuration() {
        return duration;
    }

    public long toMillis() {
        long years = period.getYears();
        long months = period.getMonths();
        long days = period.getDays();

        // Calculate total days (approximate for years and months)
        long totalDays = (long) (years * 365) + (long) (months * 28) + days;
        long periodMillis = totalDays * 24 * 60 * 60 * 1000;

        return periodMillis + duration.toMillis();
    }

    /**
     * Add another TimeSpan.
     */
    public TimeSpan plus(TimeSpan other) {
        return new TimeSpan(period.plus(other.period).normalized(), duration.plus(other.duration));
    }

    /**
     * Subtract another TimeSpan.
     */
    public TimeSpan minus(TimeSpan other) {
        return new TimeSpan(period.minus(other.period).normalized(), duration.minus(other.duration));
    }

    /**
     * String representation.
     */
    @Override
    public String toString() {
        return period.toString() + duration.toString().substring(1);
    }

    /**
     * Only equals if all values are the same.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TimeSpan timeSpan = (TimeSpan) o;
        return period.equals(timeSpan.period) && duration.equals(timeSpan.duration);
    }

    /**
     * Hash code.
     */
    @Override
    public int hashCode() {
        return period.hashCode() + duration.hashCode();
    }

    /**
     * Resolution based on contained values.
     */
    public ChronoUnit resolution() {
        if (duration.toNanosPart() != 0) return ChronoUnit.NANOS;
        if (duration.toMillisPart() != 0) return ChronoUnit.MILLIS;
        if (duration.toSecondsPart() != 0) return ChronoUnit.SECONDS;
        if (duration.toMinutesPart() != 0) return ChronoUnit.MINUTES;
        if (duration.toHoursPart() != 0) return ChronoUnit.HOURS;
        return ChronoUnit.DAYS;
    }

    /**
     * Parse the string that is generated by toString() back to an instance of TimeSpan.
     * This is also compliant with the ISO 8601 format for durations.
     */
    public static TimeSpan parse(String text) {
        String[] parts = text.split("T");
        return new TimeSpan(Period.parse(parts[0]), Duration.parse("PT" + parts[1]));
    }

    // ========== Extension functions moved to static utilities ==========

    /**
     * Convert an int to a TimeSpan of years.
     */
    public static TimeSpan years(int value) {
        return new TimeSpan(value, 0, 0, 0, 0, 0, 0L);
    }

    /**
     * Convert an int to a TimeSpan of months.
     */
    public static TimeSpan months(int value) {
        return new TimeSpan(0, value, 0, 0, 0, 0, 0L);
    }

    /**
     * Convert an int to a TimeSpan of days.
     */
    public static TimeSpan days(int value) {
        return new TimeSpan(0, 0, value, 0, 0, 0, 0L);
    }

    /**
     * Convert an int to a TimeSpan of hours.
     */
    public static TimeSpan hours(int value) {
        return new TimeSpan(0, 0, 0, value, 0, 0, 0L);
    }

    /**
     * Convert an int to a TimeSpan of minutes.
     */
    public static TimeSpan minutes(int value) {
        return new TimeSpan(0, 0, 0, 0, value, 0, 0L);
    }

    /**
     * Convert an int to a TimeSpan of seconds.
     */
    public static TimeSpan seconds(int value) {
        return new TimeSpan(0, 0, 0, 0, 0, value, 0L);
    }

    /**
     * Convert an int to a TimeSpan of milliseconds.
     */
    public static TimeSpan millis(int value) {
        return nanos((long) value * 1_000_000L);
    }

    /**
     * Convert a long to a TimeSpan of nanoseconds.
     */
    public static TimeSpan nanos(long value) {
        return new TimeSpan(0, 0, 0, 0, 0, 0, value);
    }

    /**
     * Add a period to an Instant using the provided ZoneId.
     */
    public static Instant plus(Instant instant, TimeSpan period, ZoneId zoneId) {
        // Optimized path for HFT
        if (period == TimeSpan.ZERO) return instant;
        
        Instant result;
        if (period.period.equals(Period.ZERO)) {
            result = instant;
        } else {
            result = instant.atZone(zoneId).plus(period.period).toInstant();
        }
        return result.plus(period.duration);
    }

    /**
     * Add a period to an Instant using UTC.
     */
    public static Instant plus(Instant instant, TimeSpan period) {
        return plus(instant, period, ZoneOffset.UTC);
    }

    /**
     * Subtract a period from an Instant using the provided ZoneId.
     */
    public static Instant minus(Instant instant, TimeSpan period, ZoneId zoneId) {
        // Optimized path for HFT
        if (period == TimeSpan.ZERO) return instant;
        
        Instant result;
        if (period.period.equals(Period.ZERO)) {
            result = instant;
        } else {
            result = instant.atZone(zoneId).minus(period.period).toInstant();
        }
        return result.minus(period.duration);
    }

    /**
     * Subtract a period from an Instant using UTC.
     */
    public static Instant minus(Instant instant, TimeSpan period) {
        return minus(instant, period, ZoneOffset.UTC);
    }

    /**
     * Add a period to a ZonedDateTime.
     */
    public static ZonedDateTime plus(ZonedDateTime zdt, TimeSpan period) {
        return zdt.plus(period.period).plus(period.duration);
    }

    /**
     * Subtract a period from a ZonedDateTime.
     */
    public static ZonedDateTime minus(ZonedDateTime zdt, TimeSpan period) {
        return zdt.minus(period.period).minus(period.duration);
    }
}
